### ISSUE TITLE
Option to not output "portfolio-weighted" market_share targets

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.analysis#131]
As a bank, I would like to be able to calculate the output of `target_market_share(..., by_company = FALSE)`, WITHOUT multiplying `production` by `loan_size_*` at all. 

(We would refer to this as something like "client-level view", or "portfolio-level output, without portfolio-weighting")

**Comment by jdhoffa** [comment]
@2diiKlaus

**Comment by 2diiKlaus** [comment]
@jdhoffa This was actually also talking about the volume approach. 

**The client view** is the volume trajectory using the entire company production, aggregate it at portfolio level (i.e. sum all matched companies) and normalizing it by the start year value, so that it will create a volume trajectory starting at 1.

The scenario uses the same approach but using the scenario values at the company level instead of the production values

**Comment by maurolepore** [comment]
@jdhoffa, would you like to use the project board to create the backlog and monitor each issue move to done?
https://github.com/2DegreesInvesting/r2dii.analysis/projects/1

**Comment by 2diiKlaus** [comment]
Can we change the title to "option to output an unweighted volume trend" as this is not about the technology mix

replace volume trend with production trend or whatever comes to you mind @jdhoffa

**Comment by jdhoffa** [comment]
Happy to change the title, but just FYI: I have been using the term "market share" for any type of target, where we use the "market share approach" to calculate a target (ie. volume OR tech mix)

This is in contrast with "sda" for any type of target, where (you guessed it) we use the "sda approach"
