### ISSUE TITLE
rbind() should be changed to dplyr::bind_rows() in "Get Started" page on website

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.analysis#133]
```r
> targets_and_ceiling <- just_targets %>%
+    rbind(ceiling) %>%
+    group_by(year) %>%
+    arrange(year, weighted_production_value) %>%
+    mutate(
+        previous_value = lag(weighted_production_value, default = 0),
+    ) %>%
+    filter(region == "global")

Error in UseMethod("group_by_") :
  no applicable method for 'group_by_' applied to an object of class "c('matrix', 'list')"
```

**Comment by jdhoffa** [comment]
@maurolepore Very peculiar this one... 
It works fine on the website/ on test data, but George reported this error, and said a separate bank reported similar. 
Had a call with him one on one, where we inspected the datasets one by one. On his computer, we found:
- `just_targets` is a tibble of n rows, and 7 columns 
- `ceiling` is a tibble of m rows, and 7 columns

but weirdly: 
``` r
just_targets %>%
+    rbind(ceiling)
``` 
returns a list... 
 
Switching to bind_rows() fixed the issue.

**Comment by maurolepore** [comment]
Not sure if it's worthwhile getting to the bottom of this problem, which seems unrelated to this package. 

If you do want to dig deeper, it will  help a lot to share a reproducible example with the session information -- as I suspect the problem comes from outdated packages.

See the argument `session_info` to `reprex::reprex()`: https://reprex.tidyverse.org/reference/reprex.html
