### ISSUE TITLE
the time horizon length of the market-share-target in the function "target_market_share"

### ISSUE THREAD

**Issue by QianFeng2020** [2DegreesInvesting/r2dii.analysis#140]
Hey, 

When running the function "target_market_share", the future time horizon length is determined by the time length of the global asset dataset, e.g. Terra receives global dataset is up to 2025 and the relevant generated market-share targets is until 2025 too. I assume that the targets should align with the scenario benchmark. Is that the case? 

Thanks! 
Qian

**Comment by jdhoffa** [comment]
The market share target is a moving target, and is calculated per portfolio, so for any given portfolio, it will not align with the scenario benchmark no. 

The idea is that, in aggregate, if each portfolio follows PACTA, (and contributes to the alignment efforts relative to their "market share"), the aggregate will align with the benchmark.

**Comment by QianFeng2020** [comment]
Hi Jackson, 

I see. But I assume that the target result should be until year 2060, instead of year 2025. From the SDA result, I expect that the time length of targets should be the same as the time length of the scenario data. 

Regards
Qian

**Comment by jdhoffa** [comment]
Yes that is correct. 
What I meant in the original comment is that for any year, `t`, the aggregate of all portfolio's aligning to the scenario targets should align with the scenario target at that same year, `t`. (2025 OR 2060 OR any other year). Of course this makes the (wrong) assumption that all portfolio's will follow PACTA targets, but it is an underpinning assumption of the market share method. 

The market share target is not a "convergence target" in the same that the SDA targets are. 

I hope this makes sense, it is further discussed in the methodology document. Since this is a conversation related to the methodology, and not the tool/ implementation, I'd like to move the conversation to comments on the methodology document. Happy to also keep discussing by e-mail, but I'd like to close this issue if that's ok with you.

**Comment by maurolepore** [comment]
Thanks!
