### ISSUE TITLE
Relax dependency on R 3.6.3 to R 3.6.1 

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.analysis#225]
@maurolepore not sure how possible/ likely this is, but wanted to explore! If it's easily doable, we might consider it as we've had multiple folks reach out with only 3.6.1, who are unable to easily update.

**Comment by maurolepore** [comment]
DESCRIPTION states "Depends: R >= 3.4" so I'll label this as "bug". Do we have a code snippet that exposes this dependency?

**Comment by jdhoffa** [comment]
Nope, this is all that we have: 

> Also, during our discussion with **** last Friday we also flagged an issue relating to a failure message that we cannot upload the r2ii.analysis package due to the fact that our R Studio is a 3.6.1 version while the package is said to require a 3.6.3 version. **** would come back on to give us instructions on this as he was rest assured that this issue can be easily overcome. Can you please provide us with the necessary instructions for this failure?

**Comment by maurolepore** [comment]
The cause of the problem seems unrelated to r2dii.analysis:

> ... due to the fact that our R Studio is a 3.6.1 version while the package is said to require a 3.6.3

Instead it seems like a conflict between R and RStudio. I would suggest they try  <https://community.rstudio.com/> or  <https://stackoverflow.com/>.

If they believe it is indeed a problem with r2dii.analysis, we'll need more information. We [continuously check with R back to 3.4](https://github.com/2DegreesInvesting/r2dii.analysis/blob/c923db88630966ce3ceca6e017fd0bb4c45f81d6/.github/workflows/R-CMD-check.yaml#L26) and see no problem.

**Comment by jdhoffa** [comment]
I'm 99% sure that this is just a relic of them not understanding the difference between R and RStudio. 
I don't think they actually have RStudio 3.6.3... but that said, still peculiar that we don't get that error. 

I'll call them and try to debug further.

**Comment by jdhoffa** [comment]
No more context on this, going to close as it is stale.
