### ISSUE TITLE
Brainstorm new (name,value) pairs for the output of `target_*`

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.analysis#86]
Relates to https://github.com/2DegreesInvesting/r2dii.analysis/pull/81
> Looks good. I agree we need to polish names -- not only the names of the columns but also the name of the values that get into the pivoted columns. But that's another discussion. Maybe we could do a brainstorm session and involve other folks.

**Comment by maurolepore** [comment]
I find column names too verbose. Part of the problem may be that the functions that generate the datasets have name that give little information about what to expect from the output.

Long names are difficult to work with because they take up a lot of screen space. They impair understanding the dataset they live in because they push out of the visible space many columns that provide context.

Shorter names should be clear if the name of the dataset (or function that generates the dataset) provides useful context.

For example:

It is too verbose if `r mydata %>% add_foofy()` results in the new column `mydata_foofy`; it is redundant to refer to it as `mydata$mydata_foofy()`.

It's clear enough if `r mydata %>% add_foofy()` results in the new column `foofy`; I can now refer to it as `mydata$foofy`.
